### PR TITLE
Redirect to login on 403 error page

### PR DESCRIPTION
**Pull request by James-N-M**
when a user gets a 403 error it will redirect them to the login page instead of the 403 page

### CODE REVIEW

**Comment by philippejadin** [comment]
I just need to check an issue with failing tests with this fix

**Comment by James-N-M** [comment]
cool cool :) @philippejadin

**Comment by philippejadin** [comment]
I wo'nt be able to merge this one. The exception handler code is too sensitive to touch it. I'd better have a custom 403 view being rendered as explained here : https://laravel.com/docs/5.8/errors#custom-http-error-pages

I guess a custom 403 blade page could include the login screen - only if the current user is not authenticated already.
Because sometimes, you are logged in but you really can't do some actions :-)

Do you want to work on it, or shall I continue? 

I'm currently refactoring policies / permissions / etc...

**Comment by philippejadin** [comment]
I made a fix in the latest commit, you can see it here : https://github.com/philippejadin/agorakit/commit/fd071d34b9e96ff9e6daa49cd38a24a848d92bc3

Sorry for not accepting your PR, but this way we don't touch the critical handler file. Don't hesitate to  propose more PR's btw :-)

**Comment by James-N-M** [comment]
@philippejadin thats ok ! I'm not sure if you solved this or you want me to solve it still :P also yes absolutely I'll find another to contribute to :)

**Comment by philippejadin** [comment]
@James-N-M it is solved by doing the work in a custom 403.blade.php view. It's a bit later in the render chain but it feels safer like that.

Thanks in advance for your future contributions !

**Comment by James-N-M** [comment]
cool cool :)

**Pull request closed without merging**
