### PR TITLE
Added titles to pages at the controller level 

### PR DESCRIPTION
**Pull request by James-N-M**
added title tags to group , group discussion, map and user controllers, and fixed some formatting on the existing with tags

### CODE REVIEW

**Comment by philippejadin** [comment]
This look fine, but could you use translations? You might find existing translation strings in the views. Like `trans('discussion.create_one_button')` taken from views/discussions/create/blade.php

If no suitable translation string found, don't hesitate to add one.

Thanks!

**Comment by James-N-M** [comment]
@philippejadin Sounds good thanks for the info !

**Comment by James-N-M** [comment]
updated @philippejadin :)

**Comment by James-N-M** [comment]
@philippejadin Let me know if this is ok for ya when you get a chance :)

**Comment by philippejadin** [comment]
I will do that asap, I was a bit busted those last days

Philippe Jadin

**Comment by philippejadin** [comment]
Thank you @James-N-M  works perfectly :-)

**Pull request merged**
